spacing         = 2
padding         = 0
hide_ascii      = false
separator       = ">"
key_color       = "White"
separator_color = "LightMagenta"
prefer_small_ascii = true

[palette]
type = "Full"
visible = false

[bar]
glyph           = "ß‹"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "plain"
visible         = false

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"